primary_region = 'sjc'

[http_service]
  internal_port = 80
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  protocol = 'tcp'
  internal_port = 9222
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 9222
    handlers = ['http']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 4
